"""Simple Cloud Functions web frontend for testing OAuth redirects."""
import os
from flask import Request, make_response
import functions_framework

OAUTH_LOGIN_URL = os.environ.get(
    "OAUTH_LOGIN_URL",
    "https://guidon-60g097ca.ew.gateway.dev/auth/login"
)


@functions_framework.http
def web_app(request: Request):
    """
    Minimal HTML page for OAuth login & callback display.

    Query Parameters:
        session: session identifier generated by auth-service
        user: optional username to greet
    """
    session_id = request.args.get("session")
    username = request.args.get("user", "Visitor")
    has_session = bool(session_id)
    session_display = session_id or "unknown"

    auto_redirect = ""
    if not has_session and OAUTH_LOGIN_URL:
        auto_redirect = f'<meta http-equiv="refresh" content="0;url={OAUTH_LOGIN_URL}">'

    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8" />
        {auto_redirect}
        <title>Guidon - Session</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                background: #0f172a;
                color: #f8fafc;
                display: flex;
                align-items: center;
                justify-content: center;
                min-height: 100vh;
                margin: 0;
            }}
            .card {{
                background: #1e293b;
                padding: 2rem;
                border-radius: 16px;
                box-shadow: 0 20px 45px rgba(15, 23, 42, 0.4);
                max-width: 520px;
                text-align: center;
            }}
            .session {{
                margin-top: 1rem;
                padding: 1rem;
                border-radius: 12px;
                background: rgba(59, 130, 246, 0.15);
                word-break: break-all;
                font-family: "Courier New", monospace;
            }}
            .btn {{
                display: inline-block;
                padding: 0.85rem 1.8rem;
                margin-top: 1.5rem;
                border-radius: 12px;
                background: linear-gradient(135deg, #6366f1, #3b82f6);
                color: #fff;
                text-decoration: none;
                font-weight: 600;
                box-shadow: 0 10px 25px rgba(59, 130, 246, 0.3);
                transition: transform 0.2s ease;
            }}
            .btn:hover {{
                transform: translateY(-2px);
            }}
            .muted {{
                color: #94a3b8;
                font-size: 0.9rem;
                margin-top: 1rem;
            }}
            a {{
                color: #60a5fa;
            }}
        </style>
    </head>
    <body>
        <div class="card">
            {"<h1>Welcome, " + username + "!</h1><p>Authentication succeeded. Here is your session:</p><div class='session'>" + session_display + "</div><p>Copy it to use with the API or paste it in Postman.</p>" if has_session else "<h1>Need access?</h1><p>Authenticate with Discord to obtain a session token.</p><a class='btn' href='" + (OAUTH_LOGIN_URL or '#') + "'>Login with Discord</a><p class='muted'>If the redirect did not start automatically, use the button above.</p>"}
            <small class="muted">
                Powered by Guidon • <a href="https://discord.com">Discord</a>
            </small>
        </div>
    </body>
    </html>
    """

    response = make_response(html)
    response.headers["Content-Type"] = "text/html; charset=utf-8"
    return response

