"""Web frontend for Guidon - Canvas drawing interface."""
import os
import sys
from flask import Request, make_response, jsonify
import functions_framework
import requests

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from shared.observability import init_observability, traced_function
from shared.correlation import with_correlation

logger, tracing = init_observability('web-frontend', app=None)

OAUTH_LOGIN_URL = os.environ.get(
    "OAUTH_LOGIN_URL",
    "https://guidon-60g097ca.ew.gateway.dev/auth/login"
)
GATEWAY_URL = os.environ.get(
    "GATEWAY_URL",
    "https://guidon-60g097ca.ew.gateway.dev"
)
AUTH_SERVICE_URL = os.environ.get(
    "AUTH_SERVICE_URL",
    GATEWAY_URL
)

@functions_framework.http
@with_correlation(logger)
@traced_function("web_app")
def web_app(request: Request):
    """
    Web frontend with canvas drawing interface.

    Query Parameters:
        session: session identifier generated by auth-service
        user: optional username to greet
    """
    correlation_id = getattr(request, 'correlation_id', request.headers.get('X-Correlation-ID'))

    try:
        path = request.path
        method = request.method

        logger.info("Web request received", correlation_id=correlation_id, path=path, method=method)

        # Canvas page
        path_clean = path.rstrip('/')
        if path_clean == '/canvas' or path_clean == '':
            return canvas_page(request)

        return session_page(request)
    except Exception as e:
        logger.error("Error in web_app", error=e, correlation_id=correlation_id, path=request.path)
        return make_response("Internal server error", 500)


def session_page(request: Request):
    """Legacy session display page."""
    session_id = request.args.get("session")
    username = request.args.get("user", "Visitor")
    has_session = bool(session_id)
    session_display = session_id or "unknown"

    # Load template
    template_path = os.path.join(os.path.dirname(__file__), 'template', 'session.html')
    try:
        with open(template_path, 'r', encoding='utf-8') as f:
            html = f.read()

        # Generate content based on session
        if has_session:
            content = f"""
            <h1>Welcome, {username}!</h1>
            <p>Authentication succeeded. Here is your session:</p>
            <div class='session'>{session_display}</div>
            <p>Copy it to use with the API or paste it in Postman.</p>
            <a class='btn' href='/canvas?session={session_id}'>Go to Canvas</a>
            """
        else:
            content = f"""
            <h1>Welcome to Guidon</h1>
            <p>Connect with Discord to start drawing on the shared canvas.</p>
            <a class='btn' href='{OAUTH_LOGIN_URL or "#"}'>Connect with Discord</a>
            <p class='muted'>Click the button above to authenticate with Discord.</p>
            """

        html = html.replace('{{CONTENT}}', content)
    except FileNotFoundError:
        logger.warning("Session template not found", template_path=template_path)
        html = f"<html><body><h1>Error: Template not found</h1></body></html>"

    response = make_response(html)
    response.headers["Content-Type"] = "text/html; charset=utf-8"
    return response


def verify_session(session_id: str) -> dict:
    """Verify session with auth service."""
    try:
        if not AUTH_SERVICE_URL:
            return None

        response = requests.post(
            f"{AUTH_SERVICE_URL}/auth/verify",
            json={'session_id': session_id},
            timeout=2
        )

        if response.status_code == 200:
            data = response.json()
            if data.get('valid'):
                return data.get('user')
    except Exception as e:
        logger.warning("Session verification error", error=e)
    return None


# Canvas API routes removed - frontend now uses /web/interactions directly via gateway
# All canvas operations (draw, snapshot, stats) go through the same flow as Discord:
# Frontend → Gateway → Proxy → Pub/Sub → Processor-Art → Proxy → Frontend


def canvas_page(request: Request):
    """Canvas drawing page."""
    correlation_id = getattr(request, 'correlation_id', request.headers.get('X-Correlation-ID'))
    session_id = request.args.get("session")

    try:
        # Show login page if no session
        if not session_id:
            logger.warning("Canvas page accessed without session", correlation_id=correlation_id)
            if OAUTH_LOGIN_URL:
                # Load login template
                login_template_path = os.path.join(os.path.dirname(__file__), 'template', 'login.html')
                try:
                    with open(login_template_path, 'r', encoding='utf-8') as f:
                        login_html = f.read()
                    login_html = login_html.replace('{{OAUTH_LOGIN_URL}}', OAUTH_LOGIN_URL)
                except FileNotFoundError:
                    logger.warning("Login template not found", template_path=login_template_path)
                    login_html = f"<html><body><h1>Error: Template not found</h1></body></html>"

                response = make_response(login_html)
                response.headers["Content-Type"] = "text/html; charset=utf-8"
                return response

        logger.info("Canvas page accessed", correlation_id=correlation_id, has_session=bool(session_id))

        # Load template
        template_path = os.path.join(os.path.dirname(__file__), 'template', 'canvas.html')
        try:
            with open(template_path, 'r', encoding='utf-8') as f:
                html = f.read()

            # Inject session ID and gateway URL into template
            html = html.replace(
                '<script>',
                f'''<script>
            const SESSION_ID = {repr(session_id)};
            const GATEWAY_URL = {repr(GATEWAY_URL)};
            if (SESSION_ID) {{
                localStorage.setItem('guidon_session', SESSION_ID);
            }}'''
            )
        except FileNotFoundError:
            logger.error("Canvas template not found", template_path=template_path)
            html = "<html><body><h1>Error: Canvas template not found</h1></body></html>"

        response = make_response(html)
        response.headers["Content-Type"] = "text/html; charset=utf-8"
        return response
    except Exception as e:
        logger.error("Error generating canvas page HTML", error=e, correlation_id=correlation_id)
        return make_response("Error loading canvas page", 500)

